language: python

python:
- "3.5"
- "3.6"

install:
- pip install codecov
- pip install pycodestyle
- pip install pytest-asyncio
- pip install pytest-cov

script:
- pytest --cov
- pycodestyle --exclude='old' py3blocks *.py

after_success:
- codecov
